version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: Install build tools
          command: apt-get install make
      - run:
          name: Run the test suite
          command: make check

